@startmindmap
skinparam monochrome reverse
* wODM
**_ XDisplayManager
*** HMD
****_ 通常モード: Xに接続できなければ通常モードで起動
*****_ OVRを含めてHMDを探索
*****_ 適切なHMDのインスタンスを生成
****_ 開発モード: Xに接続できたら開発モードで起動
*****_ 通常の窓を開く
*****_ HMDを探しに行かずにDummyHMDをインスタンス化
****_ インスタンス化失敗時はエラーメッセージを表示、syslogにログを出力して終了
****_ 頭の姿勢を取得
**_ wOLM起動
***_ ログイン
****_ ログインwidget
****_ PAM認証
***_ wOSH起動
****_ fork後、子プロセスで権限を切り替えてexec
****_ 起動後はログイン画面を不可視にして終了待ち
***_ 多重Xサーバ環境起動
****_ 多重Xサーバ起動
****_ X用デスクトップ環境起動
** Scenery
***_ 頭の向きを視錐体にする
***_ 陰影なし
** World
*** Actor : List<Actor>::Node
****_ 位置と向きや速度を保持
****_ Roomとの対応を維持
**** Self(自キャラ)
*****_ 姿勢と頭の姿勢を合算したものを視錐体にする
*****_ 描画の始点(対応付けられたRoomから描画)
*** Room
****_ 衝突判定
*****_ 内部にあるActorを保持、制御を渡す
*****_ Roomから出た場合
******_ 移動可能ならハンドオーバー
******_ 移動不可なら衝突
*****_ 他のActor
******_ 衝突
******_ 境界付近での判定のため隣のRoomの物体までは判定
***_ クライアントと同期
****_ 頂点データ
****_ テクスチャ
****_ ボーン
** UI
***_ 仮想画面上の頭の向きの延長にある点を中心に描画(FOVは他と共通)
*** Pane
****_ NavigationRingのために最上位Paneの反復子をstaticに確保できる
*****_ tb::List::Iはmove可能である必要がある
****_ イベント転送
****_ それ自体の操作
*****_ OnIdle
*****_ 移動
******_ Move
******_ MoveTo
******_ Jump
******_ JumpTo
*****: virtual void NotifyChildren
- 追加、削除など子要素に変化があったら通知
- 単なる順番の変更は通知されない;
*****_ 親子関係変更
*****_ 中心位置の取得(NavigationRingが使う)
*****_ Document向けインターフェイス
**** Tabs
*****_ コンテントのハンドル(子をタブとして扱う)
***** Window
******_ メニューなどを含めたウインドウコントロールを持つ
*******_ メニュー関連などのDocument向けインターフェイス(activeなPaneのものを選択)
******_ 親を指定されていなければ最上位に生成
******_ 親を指定されていたらコントロールなし(階層化タブとして使う)
******_ 子要素がなくなったら消滅
**** TexturePane
*****_ 画像転送
*****_ 表示
***** CanvasPane
******_ 描画
***** XPane
******_ X窓の保持
******_ イベントをX窓へ転送
** Stickies
***_ ヘッドトラックなし
*** NavigationRing
****_ 表示対象は最上位Paneのみ
****_ Paneの中心に対応するリング上の位置に点を表示
*****_ 点はリングの内縁が画面のその位置に対応、外縁が無限遠に対応(極軸座標系にして距離を反比例式で変換)
*****_ 通知などで点の色を変更、点滅などができる
* XWindowManager
**_ 起動後に開かれたX窓を検出
**_ 検出されたX窓をキャプチャ
**_ Window作成
**_ 検出されたX窓と作ったWindowを引数にしてXPane作成
* Document(Pane類と多重継承して使う)
**_ 保存状態の管理(何か変更したら未保存状態に)
**_ ファイルの管理(ファイル選択や別名/コピーを保存などでパスを設定したり)
**_ ドキュメントのインターフェイス
***_ 読み込み/保存
***_ シリアライズ/デシリアライズのインターフェイス
*_ UID
**_ マウス
**_ キーボード
**_ ゲームパッド
@endmindmap
