@startmindmap
skinparam monochrome reverse
* X-DisplayManager
** HMD
*** 通常モード: Xに接続できなければ通常モードで起動
****_ OVRを含めてHMDを探して起動する
*** 開発モード: Xに接続できたら開発モードで起動
****_ 通常の窓を開く
****_ HMDを探しに行かずにDummyHMDをインスタンス化
** wOLM起動
*** ログイン
**** widget
**** 認証
*** wOSH起動
*** 多重Xサーバ環境起動
****_ 多重Xサーバ起動
****_ X用デスクトップ環境起動
** オブジェクト
*** 衝突判定
*** ワールド
**** エリア構成、追跡
**** 描画
*** クライアントと同期
**** 頂点データ
**** テクスチャ
**** ボーン
** UI
*** wODM窓
****_ Window
***** ウインドウコントロール
*****_ Tab
****_ BasePane
***** イベント転送
***** 窓自体の操作
****** Update
****** Open
****** Close
****** 移動
****** 親子関係変更
*****_ TexturePane
****** 画像転送
****** 表示
******_ CanvasPane
******* 描画
*** ナビゲーションリング
* X-WindowManager
**_ XPane
*** 起動後に開かれたX窓をキャプチャ
*** 窓へのイベントをXのイベントとして窓に投げ込む
* UID
** マウス
** キーボード
** ゲームパッド
@endmindmap
